steps:
- label: "Build Docs"
  agents:
    os: "linux"
    docker: "true"
    arch: "amd64"
  command:
    - "git -C /home/opam/opam-repository pull origin master && opam update -uy"
    - "./02-install-packages.sh && ./03-generate-html.sh"
  plugins:
    docker#v1.1.1:
      image: "ocaml/opam2-staging:debian-9-ocaml-4.05"
      mounts:
        - opam2-archive:/home/opam/.opam/download-cache
      workdir: /src
      always_pull: true
      environment:
      - OPAMYES=1
      - OPAMJOBS=24
      - BUILDKITE=true
- wait
- label: "Deploy Docs"
  command:
    - "./04-push-docs.sh"
  agents:
    githubpusher: "true"
