steps:
- label: "Build Docs"
  agents:
    arch: "amd64"
    docker: "true"
    os: "linux"
  command:
    - "./01-init-opam.sh"
    - "./02-install-packages.sh"
    - "./03-generate-html.sh"
  plugins:
    docker#v1.1.1:
      image: "ocaml/opam2-staging"
      workdir: /src
      always_pull: true
      environment:
      - OPAMYES=1
      - OPAMJOBS=24
