steps:
- label: "Build Docs"
  agents:
    arch: "amd64"
    docker: "true"
    os: "linux"
    githubpusher: "true"
  command:
    - "./02-install-packages.sh && ./03-generate-html.sh && ./04-push-docs.sh"
  plugins:
    docker#v1.1.1:
      image: "ocaml/opam2-staging:debian-9-ocaml-4.05"
      workdir: /src
      always_pull: true
      environment:
      - OPAMYES=1
      - OPAMJOBS=24
